/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.query.expression.parser;

import lombok.val;
import lombok.extern.slf4j.Slf4j;
import sample.query.expression.model.Expr;

@Slf4j
public class QueryParser {

    public static Expr parse(String query) {
        val s = query.replaceAll(" ", "");
        val expr = Grammar.parse(s).getOrThrow();
        return expr;
    }
}
